add_newline = true
format = "$directory$character"

[character]
success_symbol = "[❯❯](green)"
error_symbol = "[❯❯](red)"
vimcmd_symbol = '[\[N\]](bold grey)'
vimcmd_replace_symbol = '[\[R\]](bold purple)'
vimcmd_replace_one_symbol = '[\[R\]](bold purple)'
vimcmd_visual_symbol = '[\[V\]](bold yellow)'

[battery]
disabled = true

[line_break]
disabled = false

[golang]
symbol = " "
